name: Build
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install
              run: npm install
            - name: Rust Setup
              uses: jetli/wasm-pack-action@v0.3.0
              with:
                  version: "latest"
            - name: Build
              run: npm run build-prod
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: deploy
                  FOLDER: dist
